name: py_ssdi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - networkx
  - pytest
  - pytest-cov
  - pip
  - pip:
    - control
    - slycot # optional dependency for control
    - pytest
    - pytest-cov 